config/routes.rb
Rails.application.routes.draw do
  
  wiki_root '/wiki'
  root 'users#index'
  get '/session/load' => 'session#load'
  get '/session' => 'session#destroy'
  get '/session/set' => 'session#timer'
  get '/check' => 'session#checker'
  get '/login' => 'users#login'
  get '/create' => 'users#create'
  get '/logout' => 'users#logout'
  post '/wiki' => 'wiki#new/:title'
  get '/welcome' => 'users#welcome'
  get '/create/wiki' => 'wiki_pages#new_page'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/wiki_page.rb
class WikiPage < ActiveRecord::Base
  acts_as_wiki_page
end

app/models/wiki_page_attachment.rb
require 'paperclip'

class WikiPageAttachment < ActiveRecord::Base
  acts_as_wiki_page_attachment do
    has_attached_file :wiki_page_attachment, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_presence :wiki_page_attachment, message: " is missing."
    validates_attachment_content_type :wiki_page_attachment, content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/x-png', 'image/gif', 'image/pjpeg'], message: ' must be a JPEG, PNG or GIF.'
  end
end

app/models/wiki_page_version.rb
class WikiPageVersion < ActiveRecord::Base
  acts_as_wiki_page_version
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def load
    
  end
  def timer
    cookies[:promo] = { value: "activated", expires: 1.minute.from_now }
  end
  def destroy
    cookies.clear
  end
  def checker
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def login 
    @user = User.find_by_email(params[:email])
    session[:user] = @user
  end
  def create
    @user = User.create(first_name:params[:first_name], last_name:params[:last_name], email:params[:email], password:params[:password])
    if @user.save == true
      redirect_to '/welcome'
    else
      redirect_to '/'
    end
  end
  def logout
    session[:user] = nil
    redirect_to '/'
  end
  def upload
  end
  def welcome
    @user = User.last()
  end
end

app/controllers/wiki_pages_controller.rb
class WikiPagesController < ApplicationController

acts_as_wiki_pages_controller
  def new_page
    @title = params[:title]
    redirect_to "/wiki/new/#{@title}"
  end
  # def show_allowed?
  #   # true # Show page to all users
  # end

  # def history_allowed?
  #   # true # Show history to all users
  # end

  # def edit_allowed?
  #   # current_user ? true : false # Allow editing only to logged users
  # end

  # def destroy_allowed?
  #     # @page.path != '' && current_user && current_user.admin? 
  #     # Allow editing only to admins, and not to root page
  # end

  # def not_allowed
  #   # redirect_to login_path # Redirect to login_url when user tries something what not allowed
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wiki_pages_helper.rb
module WikiPagesHelper
  acts_as_wiki_pages_helper
end

app/views/base_wiki_pages/_wiki_page_actions.html.erb
<ul class="wiki_page_actions">
  <%= content_tag('li', link_to( wt( 'List pages' ), wiki_all_path)) %>
  <%= content_tag('li', link_to( wt( 'History' ), wiki_page_history_path(@page) )) if history_allowed? %>
  <%= content_tag('li', link_to( wt( 'Create'), wiki_page_new_path )) %>
  <%= content_tag('li', link_to( wt( 'Edit' ), wiki_page_edit_path(@page) )) if edit_allowed? %>
  <%= content_tag('li', link_to( wt( 'Destroy' ), wiki_page_path(@page), :method => :delete, :confirm => wt( "Destroyed page can't be restored. Are you sure?" ) )) if destroy_allowed? %>
</ul>

app/views/base_wiki_pages/_wiki_page_attachments.html.erb
<% page.attachments.each do |attachment| %>
  <%= image_tag(attachment.wiki_page_attachment.url(:thumb)) %>
  Attachment_<%= attachment.id %>
  <%= link_to(wt('Remove'), wiki_remove_page_attachment_path(attachment.id), method: :delete) %>
<% end %>

<%= form_for(Irwi.config.page_attachment_class.new,
             as: :wiki_page_attachment,
             url: wiki_add_page_attachment_path(page),
             html: { multipart: true }) do |form| %>
  <%= form.file_field :wiki_page_attachment %>
  <%= form.hidden_field :page_id, value: page.id %>
  <%= form.submit 'New Attachment' %>
<% end %>

app/views/base_wiki_pages/_wiki_page_history.html.erb
<% if with_form %>
  <form action="<%=wiki_page_compare_path(@page)%>" method="get">
<% end %>

<%= wiki_paginate versions do -%>
<table class="wiki_history">
  <tr class="wiki_history_header">
    <td><%=wt 'Version' %></td>
    <td><%=wt 'Date' %></td>
    <td><%=wt 'Author' %></td>
    <td><%=wt 'Comment' %></td>
  </tr>
  <% versions.each do |v| %>
    <tr>
      <td>
        <%=v.number%>
        <% if with_form %>
          <input type="radio" name="old" value="<%=v.number%>" <%= 'checked="true" ' if v == versions[-1] %>/>
          <input type="radio" name="new" value="<%=v.number%>" <%= 'checked="true" ' if v == versions[-2] %>/>
        <% end %>
      </td>
      <td><%=l( v.updated_at, :format => :long ) %></td>
      <td><%= wiki_user( v.updator ) %></td>
      <td><%= v.comment %></td>
    </tr>
  <% end %>
</table>
<% end %>

<% if with_form %>
  <%= submit_tag wt 'Compare selected versions' %>
  </form>
<% end %>

app/views/base_wiki_pages/_wiki_page_info.html.erb
<div class="wiki_page_info">
  <%=(wt "Revised on %{time} by %{user}", :time => l( page.updated_at, :format => :long ), :user => wiki_user( page.updator ) ).html_safe %>
</div>

app/views/base_wiki_pages/_wiki_page_style.html.erb
<style>

.wiki_page_info {
  font-style: italic;
  color: #666;
  margin-left: 5px; 
  float: left;
}

.wiki_page_actions {
  text-align: right;
  width: 100%;
  padding: 0px;
}

.wiki_page_actions li {
  display: inline;
  margin: 0px;
  padding: 0px;
}

.wiki_content,
.wiki_diff,
.wiki_history {
  border: 1px dashed #666;
  margin-top: 10px;
  margin-bottom: 10px;
  padding: 10px;
}

.wiki_history {  
  width: 100%;
}

.wiki_history_header td {
  border-bottom: 2px dashed black; 
}

.wiki_form {
  display: block;
  width: 100%;
  border: 1px dashed #666;
}

.wiki_form p {
  padding: 10px;
}

.wiki_form p input,
.wiki_form p textarea {
  width: 100%;
}

.wiki_form .submit {
  margin-left: 20px;
  margin-bottom: 10px;
}

.wiki_diff span.added {
  background: #D4FFAB;
  color: #509A05;
}

.wiki_diff span.removed {
  background: #FFD8D8;
  color: #EF2828;
}

</style>

app/views/base_wiki_pages/all.html.erb
<%= wiki_page_style -%>
<a href="/">Home</a>
<h1><%=wt 'All pages' %></h1>

<ul>
  <%= wiki_paginate @pages do -%>
    <% @pages.each do |page| -%>
      <li><%= link_to page.title, wiki_page_path( page ) %></li>
    <% end -%>
  <% end -%>
</ul>

app/views/base_wiki_pages/compare.html.erb
<%= wiki_page_style %>

<h1><%=wt '%{page_title} - Comparing versions %{old_version} and %{new_version}', :page_title => h( @page.title ), :old_version => @old_version.number, :new_version => @new_version.number %></h1>

<%= link_to "Back to history", history_wiki_page_path(@page.path) %><br />

<%=wt 'Changes list:' %>

<%= wiki_paginate @versions do%>
  <%= wiki_page_history @page, @versions %>
<% end %>

<%=wt 'Changes in content:' %>

<div class="wiki_diff">
  <%= wiki_diff @old_version.content, @new_version.content %>
</div>

app/views/base_wiki_pages/edit.html.erb
<%= wiki_page_style %>

<h1><%=wt 'Editing wiki page' %></h1>

<% if params[:preview] %>
<div class="wiki_content">
  <%=wiki_content @page.content %>
</div>
<% end %>

<%= wiki_page_form do |f| %>
  <%= f.hidden_field :previous_version_number, :value => f.object.last_version_number %>
  <%= hidden_field_tag :path, @page.path %>

  <p><%=wt 'Title:' %><br /><%= f.text_field :title %></p>

  <%# If our 'content' contains newlines, Erubis will indent them (to make the
      produced HTML look nicer). However those indenting spaces *will* appear
      in the textarea in the user's browser and will get POSTed by the browser
      when submitting the form and thus would get written to the wiki content
      into the database.  The gsub's below replace the linebreaks ('\r\n')
      with UTF8 linefeeds (same way HAML solves this problem), which are
      ignored by Erubis and should be correctly displayed as linebreaks by
      modern browsers. %>
  <p><%=wt "Content: #{link_to('(Textile Markup', 'http://redcloth.org/hobix.com/textile/', target: '_blank')}".html_safe %> allowed)<br /><%= f.text_area(:content) %> </p>
  <%#<p><%#=wt 'Content:' %><br /><%#= f.text_area(:content, :value => f.object.content.gsub("\n", '&#x000A;').gsub("\r",'')).html_safe %#></p>%>
  <p><%=wt 'Comment on this change (optional):' %><br /><%= f.text_field :comment %></p>
  <input type="submit" name="save" value="<%=wt 'Save page' %>" class="submit" />
  <input type="submit" name="preview" value="<%=wt 'Preview' %>" class="submit" />
  <input type="submit" name="cancel" value="<%=wt 'Cancel' %>" class="submit" />
<% end %>

<%= wiki_page_attachments(@page) %>

app/views/base_wiki_pages/history.html.erb
<%= wiki_page_style %>

<h1><%=wt '%{page_title} - History', :page_title => @page.title %></h1>
  
<%= wiki_page_info %>
<%= wiki_page_actions %>

<%= wiki_page_history %>

<%= link_to "Back to page", wiki_page_path(@page) %>

app/views/base_wiki_pages/new.html.erb
<%= wiki_page_style %>

<h1><%=wt 'Creating a new wiki page' %></h1>

<%= wiki_page_form do |f| %>
  <%= f.hidden_field :previous_version_number, :value => f.object.last_version_number %>
  
  <p><%=wt 'Title:' %><br /><%= f.text_field :title %></p>
  <p><%=wt 'Content:' %><br /><%= f.text_area :content %></p>
  <%= f.hidden_field :comment, :value => 'First Revision'%>
  <%= hidden_field_tag :path, @page.path %>

  <input type="submit" value="<%=wt 'Create page' %>" class="submit" />
<% end %>

app/views/base_wiki_pages/no.html.erb
<%=(wt 'There is no such page', :default => 'There is no such page. Do you want to <a href="%{new_url}">create it</a>?', :new_url => wiki_page_new_path ).html_safe %>  

app/views/base_wiki_pages/not_allowed.html.erb
<%=wt 'You are not allowed to be here; please go back.' %>  

app/views/base_wiki_pages/show.html.erb
<%= wiki_page_style %>
<div class='container'>
  
  <h1><%=h @page.title %></h1>
    
  <%= wiki_page_info %>
  <%= wiki_page_actions %>
    
  <div class="wiki_content">
    <%=wiki_content @page.content %>
  </div>
  <%= wiki_page_attachments %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Session</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
  
<%= yield %>

</div>
</body>
</html>

app/views/session/_banner.html.erb
<div class="container">
  <div class="w-section banner-section">
    <div class="w-row">
      <div class="w-col w-col-9 w-col-small-9 w-col-tiny-9 w-clearfix head-banner-columns">
      

        <h3 class="header-banner">$5.99 FedEx Ground Shipping Special!</h3><p class="white-disclaimer">Valid on orders over $59.99 in the contiguous US only. Valid until 7/15/16. <a id='popUp'><i class="fa fa-exclamation-circle" aria-hidden="true"></i> More details.</a></p>
      </div>
      <div class="w-col w-col-3 w-col-small-3 w-col-tiny-3">
        <form action='/session' name='session'>
          <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
          <input type="submit" name="kill" value='kill'>
        </form>
        <form action='/session/set' name='session'>
          <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
          <input type="submit" name="set" value='set'>
        </form>
        <form action='/session/load' name='session'>
          <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
          <input type="submit" name="load" value='load'>
        </form>
        <form action='/check' name='checker'>
          <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
          <input type="submit" name="checker" value='checker'>
        </form>
      </div>
    </div>
  </div>
</div>

<div class='hideMe' id='details'>
  <p>Our summer shipping special uses FedEx ground. Orders shipped to the contiguous US stated including $59.99 or more of RAM Products qualify for $5.99 FedEx Ground Shipping. This offer excludes Hawaii, Alaska & U.S. Territories. </p>

  <p>To place an order online, do the following:<br>
  1. Add at least $59.99 to your Shopping Cart. <br>
  2. Upon checkout (after adding your address) select FedEx Ground Shipping.<br></p>
</div>

app/views/session/_banner2.html.erb
<div class="container">
  <div class="w-section banner-section">
    <div class="w-row">
      <div class="w-col w-col-9 w-col-small-9 w-col-tiny-9 w-clearfix head-banner-columns">
      

        <h3 class="header-banner">222 $5.99 FedEx Ground Shipping Special!</h3><p class="white-disclaimer">Valid on orders over $59.99 in the contiguous US only. Valid until 7/15/16. <a id='popUp'><i class="fa fa-exclamation-circle" aria-hidden="true"></i> More details.</a></p>
      </div>
      <div class="w-col w-col-3 w-col-small-3 w-col-tiny-3">
        <form action='/session' name='session'>
          <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
          <input type="submit" name="kill" value='kill'>
        </form>
        <form action='/session/load' name='session'>
          <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
          <input type="submit" name="load" value='load'>
        </form>
         <form action='/session/set' name='session'>
          <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
          <input type="submit" name="set" value='set'>
        </form>
        <form action='/check' name='checker'>
          <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
          <input type="submit" name="checker" value='checker'>
        </form>
      </div>
    </div>
  </div>
</div>

<div class='hideMe' id='details'>
  <p>Our summer shipping special uses FedEx ground. Orders shipped to the contiguous US stated including $59.99 or more of RAM Products qualify for $5.99 FedEx Ground Shipping. This offer excludes Hawaii, Alaska & U.S. Territories. </p>

  <p>To place an order online, do the following:<br>
  1. Add at least $59.99 to your Shopping Cart. <br>
  2. Upon checkout (after adding your address) select FedEx Ground Shipping.<br></p>
</div>

app/views/session/checker.html.erb
<h1><%= cookies[:promo] %></h1>
<h2><%= Time.now %></h2>

app/views/session/destroy.html.erb
<h1>Session</h1>
<p><%= cookies[:promo] %></p>
<% if cookies[:promo] %>
  <%= render 'banner' %>
  <% else %>
  <%= render 'banner2' %>
<% end %>

app/views/session/load.html.erb
<div class='jumbotron'>
<h1>Session</h1>
</div>
<p><%= cookies[:promo] %></p>

<% if !cookies[:promo] %>
  <%= render 'banner2' %>
  <% else %>
  <%= render 'banner' %>
<% end %>

app/views/session/timer.html.erb
<h1>Session</h1>
<p><%= cookies[:promo] %></p>

<% if !cookies[:promo] %>
  <%= render 'banner2' %>
  <% else %>
  <%= render 'banner' %>
<% end %>

app/views/users/index.html.erb
<div class='container'>
  <!-- <h1>WaRAMty&trade;</h1>
  <h2>Login</h2>
  <form action='login'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="text" name="email" placeholder='Email'>
    <input type="password" name="password" placeholder='Password'>
    <input type="submit" name="submit" class='btn btn-primary'>
  </form>
  <h2>Create</h2>
  <form action='/create'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="text" name="first_name" placeholder="First Name">
    <input type="text" name="last_name" placeholder="Last Name">
    <input type="text" name="email" placeholder='Email'>
    <input type="password" name="password" placeholder='Password'>
    <input type="submit" name="submit" class='btn btn-primary'>
  </form>
  <hr> -->
  <h1>Wiki Stuff</h1>
 Create new Wiki Page here!
  <form action='/create/wiki'>
    <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
    <label>Title</label>
    <input type="text" name="title">
    <input type="submit" name="submit" value='Create'>
  </form>
</div>

app/views/users/login.html.erb
<div class='container'>
  <h1>Welcome <%= @user[:first_name] %></h1> <a href="/logout" class='btn btn-secondary'>Log Out</a>
  <h4>Start your claim</h4>
  <%= form_for @user, url: {action: "create"} do |person_form| %>
  <%= person_form.text_field :first_name %>
  <% end %>
</div>

app/views/users/test.html.erb
<img src="../../assets/images/healthcare-background.jpg">

  <div class='container'>
    <h1 class='white2 bigFont'>Healthcare Mounts</h1>
  </div> <!-- End of Header -->
  <div class='section'>
    <div class='container transparent-bars-header'>
      <div class='section black right'>
        <h2 class='black2'>Flexible and Friendly Mounts for Demanding Environments</h2>
      </div>
      <div class='container bgWhite'>
        <div class='col col-7 clearfix'>
          <p class=''>
          RAM® Mounts has a full suite of mounting solutions for wheel chairs, scanner, medical carts and hospital beds. The innovative ball-and-socket design utilizes a patented rubber-coated ball providing superior hold and vibration reduction.</p><p> Designed to be impact resistant and adapt to any situation, RAM® Mounts are made in the U.S.A. and most products are backed with a lifetime warranty.</p>
        </div>
        <div class="col col-5 col-medium-5 clearfix">
          <img src="/images/industries/thumbs/healthcare-thumb.jpg" class='support' alt='Healthcare'>
          <div class="bookmark"><a class="breadcrumb-link" href="/industry/">Industry</a>&nbsp;// Healthcare</div>
          <div>
          Contact our Experts to help you create a fleet mounting solution.
          </div>
          <div class="clearfix assistant-button">
            <a href="#expert" class="assistant">Expert Mounting Advice</a>
            <div class="arrow">+</div>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- End of top Content -->
  <navigation>
    <div class=''>
      <div class='section transparent-nav-bar'>
        <div class='mount-menu'>
          <div class='row'>
            <div class="col col-3">
              <div class="device-icon-block">
                  <a href='#intelliskin' id='showIntelliSkin' class="phone-mount-menu">IntelliSkin with GDS Tech</a>
              </div>
            </div>
            <div class="col col-3">
              <div class="device-icon-block">
                <a href='#provenValue' id="seeValue" class="phone-mount-menu">Proven Value</a>
              </div>
            </div>
            <div class="col col-3">
              <div class="device-icon-block">
                <a href='#popular-products' id='items' class="phone-mount-menu">Popular Products</a>
              </div>
            </div>
            <div class="col col-3">
              <div class="device-icon-block">
                <a href="#expert" id='help' class="phone-mount-menu">Ask an Expert</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- End of Nav bar -->
  </navigation>

  <div id='intelliskin' class='section'>
    <div class="container">
      <div class='col clearfix transparent-bars-header'>
        <div class='section black'>
          <h2 class='fontGreen'>IntelliSkin™ with GDS™ Tech for Healthcare</h2>
        </div>
        <div class='container bgGreen'>
          <div class="col flex-gallery">
            <div class="col col-8 clearfix">
              <p class='white'>
              IntelliSkin™ is a protective device case that features an integrated power connector compatible with any GDS™ charging dock. This prevents damage to the device charging port and creates a universal docking platform compatible with any device wrapped with an IntelliSkin&trade; case. </p>
              <p class='white'>IntelliSkin&trade; ruggedizes the consumer devices that are permeating every vertical and adds functionality by simplifying the frequent docking and undocking of smartphones and tablets. IntelliSkin&trade; and GDS&trade; fit into your business operations through our ability to customize a mounting solution that fits how you do business.</p>
              <div class="row">
                <div class="col col-6 clearfix">
                  <a href="#expert" class="button buttons-on-white">Talk with an IntelliSkin Expert</a>
                </div>
                <div class="col col-6 flex-thumbs">
                  <img src="/images/industries/intelliskin/aviation.jpg">
                  <img src="/images/products/intelliskin/accessories4.jpg">
                  <img src="/images/products/intelliskin/accessories3.jpg">
                  <img src="/images/products/intelliskin/tablet1.jpg">
                </div>
              </div>
            </div>
            <div class="col col-3 flex-image right">
              <img src="/images/industries/intelliskin/aviation.jpg" class="rounded" alt="Tablet with IntelliSkin and Vehicle Dock with Windshield Mount in Cockpit">
            </div>
          </div>
        </div> <!-- End of White Block -->
      </div> <!-- End of Transparent -->
    </div> <!-- End of First Container -->
  </div> <!-- End IntelliSkin Section -->


  <div id='provenValue' class='section'>
    <div class='container'>
      <div class="section section-grey transparent-bars">
        <h2 class='black2'>Healthcare Partners</h2>

        <div class="clearfix container bgWhite">
          <div class="solutions-text white">RAM® Mounts are used across numerous airline. Contact us to see how RAM® Mounts will fit your needs.</div>
          <div class="row">
            <div class="col col-3">
              <img src="/images/industries/healthcare/permobile.jpg" class="center" alt='permobile'>
            </div>
            <div class="col col-3">
              <img src="/images/industries/healthcare/prime-mobility.jpg" class="center" alt='Pride Mobility Scooters'>
            </div>
            <div class="col col-3">
              <img src="/images/industries/healthcare/sunrise-scooters.png" class="center" alt='Sunrise Medical'>
            </div>
            <div class="col col-3">
              <img src="/images/industries/healthcare/samsung.png" class="center" alt='Samsung'>
            </div>
          </div>
        </div> <!-- End of White Box -->
      </div> <!-- End of Transparent bar -->
    </div> <!-- End of Container -->
  </div> <!-- End of Proven Value -->

  <div class='section'>
    <div class='container'>
      <div id='popular-products' class='col clearfix transparent-bars'>
        
      </div>
    </div>
  </div><!-- End of popular products -->


  <div class='section'>
    <div class='container'>
      <div id='popular-products' class='col clearfix transparent-bars'>
        
      </div>
    </div>
  </div><!-- End of popular products -->


  <div class='section'>
    <div class='container'>
      <div id="expert" class="section section-grey transparent-bars">
        <h2 class='black2'>Consult with an Expert</h2>
        <div class="clearfix container bgWhite">
          <p>We take a consultative approach with our customers. Submit your contact information and an industry-specific product specialist will contact you to review your needs and work with you to build solutions specific to your operation.</p>

          <form action="https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">

          <input type=hidden name="oid" value="00DA0000000IMDm">
          <input type=hidden name="retURL" value="http://www.rammount.com/thanks">
          <input type=hidden name="00NA0000000kjGy" value="Commercial Trucking">
          <input type=hidden name="lead_source" value="Website">

          <div class="form">
            <form id="email-form" name="email-form" data-name="Email Form">
              <div class="row">
                <div class="col col-2">
                  <label for="name" class="field-name-left">First Name</label>
                </div>
                <div class="col col-10">
                  <input id="name" type="text" placeholder="First Name" name="first_name" data-name="First Name" class="input first_name">
                </div>
              </div>
              <div class="row">
                <div class="col col-2">
                  <label for="name" class="field-name-left">Last Name</label>
                </div>
                <div class="col col-10">
                  <input id="name-4" type="text" placeholder="Last Name" name="last_name" data-name="Last Name" class="input last_name">
                </div>
              </div>
              <div class="row">
                <div class="col col-2">
                  <label for="email">Company</label>
                </div>
                <div class="col col-10">
                  <input id="email" type="text" placeholder="Your company or organization" name="company" data-name="Company" required="required" class="input company">
                </div>
              </div>
              <div class="row">
                <div class="col col-2">
                  <label for="name-2">Email Address</label>
                </div>
                <div class="col col-10">
                  <input id="email-2" type="email" placeholder="Your Email" name="email" data-name="email" class="input">
                </div>
              </div>
              <div class="row">
                <div class="col col-2">
                  <label for="name-3">Phone</label>
                </div>
                <div class="col col-10">
                  <input id="phone" type="text" placeholder="Best # to reach you at" name="phone" data-name="Phone" class="input phone">
                </div>
              </div>
              <div class="row">
                <div class="col col-2">
                  
                </div>
                <div class="col col-10">
                  <label for="field">How would you like us to help you?</label>
                  <textarea id="description" placeholder="" name="description" class="input description"></textarea>



                  <input type="submit" value="Submit" data-wait="Please wait..." class="button submit-button">
                </div>
              </div>
            </form>
           
          </div> <!-- End of Form -->

        </form>
        </div>
      </div> <!-- End of form Section -->
    </div> <!-- End of Container -->
  </div> <!-- End of Section -->

<!-- End of Section -->

<!-- End of Blue Bar -->

app/views/users/welcome.html.erb
<div class='container'>
Welcome <%= @user.first_name %>

<a href="/wiki/all">Go to Wiki</a>
Create new Wiki Page here!
  <form action='/create/wiki'>
    <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
    <label>Title</label>
    <input type="text" name="title">
    <input type="submit" name="submit" value='Create'>
  </form>
</div>